#57 fix error handling (#62)

diff --git a/aws/Push-Staging-Images-To-ECR.yaml b/aws/Push-Staging-Images-To-ECR.yaml
--- a/aws/Push-Staging-Images-To-ECR.yaml
+++ b/aws/Push-Staging-Images-To-ECR.yaml
@@ -64,7 +64,7 @@ phases:
           # Codebuild doesn't support "-" in source identifier names
           SRC_DIR=CODEBUILD_SRC_DIR_$(echo $repo | tr '-' '_')
           echo "[INFO] cd ${!SRC_DIR}"
-          cd ${!SRC_DIR} || { echo "Failed to change directory"; exit 1; }
+          cd ${!SRC_DIR} || { echo "[ERROR] Failed to change directory"; exit 1; }
 
           if [[ $repo =~ "xterm" || $repo =~ "sshd" ]]; then
             BASE="public.ecr.aws/senzing/senzingapi-tools:staging"
@@ -75,6 +75,6 @@ phases:
           $CODEBUILD_SRC_DIR/aws/docker-build.sh \
                               -a "--build-arg BASE_IMAGE=${BASE} --build-arg SENZING_APT_INSTALL_TOOLS_PACKAGE=senzingapi-tools=${SENZING_VERSION}" \
                               -t "senzing/${repos[$repo]}:staging"
-          test $? -eq 0 || echo "[ERROR] docker build failed"
+          test $? -eq 0 || { echo "[ERROR] docker build failed"; exit 1; }
 
         done
