#57 test

diff --git a/aws/Push-Staging-Images-To-ECR.yaml b/aws/Push-Staging-Images-To-ECR.yaml
--- a/aws/Push-Staging-Images-To-ECR.yaml
+++ b/aws/Push-Staging-Images-To-ECR.yaml
@@ -64,7 +64,7 @@ phases:
           # Codebuild doesn't support "-" in source identifier names
           SRC_DIR=CODEBUILD_SRC_DIR_$(echo $repo | tr '-' '_')
           echo "[INFO] cd $CODEBUILD_SRC_DIR_$(echo $repo | tr '-' '_')"
-          cd "$CODEBUILD_SRC_DIR_$(echo $repo | tr '-' '_')" || { echo "Failed to change directory"; exit 1; }
+          cd ${CODEBUILD_SRC_DIR}_$(echo $repo | tr '-' '_') || { echo "Failed to change directory"; exit 1; }
 
           if [[ $repo =~ "xterm" || $repo =~ "sshd" ]]; then
             BASE="public.ecr.aws/senzing/senzingapi-tools:staging"
